In [7]:
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

In [ ]:
#the athletes dataset
# Count the total number of medals won by each country and show the top 5.
pd.read_sql(
    """
    SELECT *
    FROM athletes_table;
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,None
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",None
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",None
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,None
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,None

In [27]:
pd.read_sql(
    """
    SELECT Team, COUNT(Medal) as Total_Medals --Using total_medals alias to make it easy to order from highest to lowest--
    FROM athletes_table
    WHERE Medal != 'None' --ensuring columns with 'none' are not counted--
    GROUP BY Team --to print output in countries--
    ORDER BY Total_Medals DESC --recording from highst to lowest number--
    LIMIT 5;
    """,
    conn
)
#

            Team  Total_Medals
0  United States          5219
1   Soviet Union          2451
2        Germany          1984
3  Great Britain          1673
4         France          1550

In [46]:
#Calculate the average age of athletes who won a Gold medal.
pd.read_sql(
    """
    SELECT AVG(Age) as Average_Age
    FROM athletes_table
    WHERE Medal = 'Gold'; --ensuring only those with gold are counted--
    """,
    conn
)

   Average_Age
0    25.901013

In [47]:
#How many distinct events are there in each sport?
pd.read_sql(
    """
    SELECT DISTINCT Event, Sport
    FROM athletes_table
    GROUP BY Sport; --satisfying the each sport parameter--
    """,
    conn
)

                                                Event             Sport
0                       Aeronautics Mixed Aeronautics       Aeronautics
1                        Alpine Skiing Men's Downhill     Alpine Skiing
2                             Alpinism Mixed Alpinism          Alpinism
3                          Archery Women's Individual           Archery
4   Art Competitions Mixed Sculpturing, Unknown Event  Art Competitions
..                                                ...               ...
61                        Tug-Of-War Men's Tug-Of-War        Tug-Of-War
62                        Volleyball Men's Volleyball        Volleyball
63                        Water Polo Men's Water Polo        Water Polo
64            Weightlifting Women's Super-Heavyweight     Weightlifting
65     Wrestling Men's Light-Heavyweight, Greco-Roman         Wrestling

[66 rows x 2 columns]

In [ ]:
#Show all athletes from the United States (NOC = 'USA').
pd.read_sql(
    """
    SELECT DISTINCT Name, NOC --disctinct keyword so that an athlete appears only once--
    FROM athletes_table
    WHERE NOC = 'USA';
    """, conn
)

                            Name  NOC
0                Per Knut Aaland  USA
1                   John Aalberg  USA
2           Stephen Anthony Abas  USA
3            David "Dave" Abbott  USA
4                  Jeremy Abbott  USA
...                          ...  ...
9647           Frank Thomas Zuna  USA
9648         David Santos Zuniga  USA
9649                    Rami Zur  USA
9650  Victor Andrew "Vic" Zwolak  USA
9651  James Francis "Jim" Zylker  USA

[9652 rows x 2 columns]

In [ ]:
#Count how many medals were awarded each year.
pd.read_sql(
    """
    SELECT COUNT(Medal), Year --showing the number of medals plus year of award--
    FROM athletes_table
    WHERE Medal != 'None' --excludes all entries with none--
    GROUP BY Year;
    """, conn
)

    COUNT(Medal)  Year
0            143  1896
1            604  1900
2            486  1904
3            458  1906
4            831  1908
5            941  1912
6           1308  1920
7            962  1924
8            823  1928
9            739  1932
10          1025  1936
11           987  1948
12          1033  1952
13          1043  1956
14          1058  1960
15          1215  1964
16          1256  1968
17          1414  1972
18          1531  1976
19          1602  1980
20          1698  1984
21          1845  1988
22          2030  1992
23           331  1994
24          1842  1996
25           440  1998
26          2004  2000
27           478  2002
28          2001  2004
29           526  2006
30          2048  2008
31           520  2010
32          1941  2012
33           597  2014
34          2023  2016

In [ ]:
#Find all athlete records where height or weight is missing.
pd.read_sql(
    """SELECT *
    FROM athletes_table
    WHERE Height IS NULL OR Weight IS NULL; --checking both height or weight in one line--
    """, conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,None
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None

In [87]:
#Replace the missing height with the average athlete height.
pd.read_sql(
    """
    SELECT ID, Name, Age, Weight, Team, Height,
    COALESCE(Height, (SELECT AVG(Height) FROM athletes_table)) AS New_Height --replace the height with average height value where missing--
    FROM athletes_table;
    """, conn
)

,ID,Name,Age,Weight,Team,Height,New_Height
0,1,A Dijiang,24.0,80.0,China,180.0,180.00000
1,2,A Lamusi,23.0,60.0,China,170.0,170.00000
2,3,Gunnar Nielsen Aaby,24.0,NaN,Denmark,NaN,175.33897
3,4,Edgar Lindenau Aabye,34.0,NaN,Denmark/Sweden,NaN,175.33897
4,5,Christine Jacoba Aaftink,21.0,82.0,Netherlands,185.0,185.00000
...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,29.0,89.0,Poland-1,179.0,179.00000
271112,135570,Piotr ya,27.0,59.0,Poland,176.0,176.00000
271113,135570,Piotr ya,27.0,59.0,Poland,176.0,176.00000
271114,135571,Tomasz Ireneusz ya,30.0,96.0,Poland,185.0,185.00000
271115,135571,Tomasz Ireneusz ya,34.0,96.0,Poland,185.0,185.00000

In [64]:
#The sales dataset: where necessary, use the key word CAST to remove the $ sign from the item_price
df_prices = pd.read_sql(
    """
    SELECT *,
    CAST(REPLACE(item_price, '$', '') AS REAL) AS Prices --replacing $ with nothing--
    FROM sales_table;
    """, conn
)
df_prices.head()

,order_id,quantity,item_name,choice_description,item_price,Prices
0,1,1,Chips and Fresh Tomato Salsa,None,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [69]:
#Return total sales value per item.
pd.read_sql(
    """
    SELECT item_name, SUM(quantity * CAST(REPLACE(item_price, '$', '') AS REAL)) AS total_sales_value
    FROM sales_table
    GROUP BY item_name;
    """, conn
)

                                item_name  total_sales_value
0                       6 Pack Soft Drink             369.93
1                           Barbacoa Bowl             672.36
2                        Barbacoa Burrito             894.75
3                   Barbacoa Crispy Tacos             138.71
4                     Barbacoa Salad Bowl             106.40
5                     Barbacoa Soft Tacos             250.46
6                           Bottled Water             649.18
7                                    Bowl              74.00
8                                 Burrito              44.40
9                             Canned Soda             191.84
10                      Canned Soft Drink             603.75
11                          Carnitas Bowl             830.71
12                       Carnitas Burrito             616.33
13                  Carnitas Crispy Tacos              95.94
14                         Carnitas Salad               8.99
15                    Carnitas Salad Bowl              66.34
16                    Carnitas Soft Tacos             375.94
17                           Chicken Bowl            8044.63
18                        Chicken Burrito            6387.06
19                   Chicken Crispy Tacos             524.11
20                          Chicken Salad              81.09
21                     Chicken Salad Bowl            1506.25
22                     Chicken Soft Tacos            1199.01
23                                  Chips             580.34
24           Chips and Fresh Tomato Salsa            1033.96
25                    Chips and Guacamole            2475.62
26      Chips and Mild Fresh Tomato Salsa               3.00
27     Chips and Roasted Chili Corn Salsa              73.75
28     Chips and Roasted Chili-Corn Salsa              43.02
29  Chips and Tomatillo Green Chili Salsa             144.55
30    Chips and Tomatillo Red Chili Salsa             159.30
31  Chips and Tomatillo-Green Chili Salsa              88.43
32    Chips and Tomatillo-Red Chili Salsa              93.21
33                           Crispy Tacos              14.80
34                                   Izze              67.80
35                       Nantucket Nectar             111.87
36                                  Salad              14.80
37                          Side of Chips             290.68
38                             Steak Bowl            2479.81
39                          Steak Burrito            4236.13
40                     Steak Crispy Tacos             375.32
41                            Steak Salad              35.66
42                       Steak Salad Bowl             391.15
43                       Steak Soft Tacos             554.55
44                            Veggie Bowl             901.95
45                         Veggie Burrito            1002.27
46                    Veggie Crispy Tacos               8.49
47                           Veggie Salad              50.94
48                      Veggie Salad Bowl             182.50
49                      Veggie Soft Tacos              90.94

In [74]:
#Show the top 5 records with the highest item_price
pd.read_sql(
    """
    SELECT CAST(REPLACE(item_price, '$', '') AS REAL) AS prices
    FROM sales_table
    ORDER BY prices DESC
    LIMIT 5;
    """, conn
)

   prices
0   44.25
1   35.25
2   35.00
3   35.00
4   33.75

In [76]:
#How many unique customer orders are there? (Assume each order_id is a customer.)
pd.read_sql(
    """
    SELECT COUNT(DISTINCT order_id) AS unique_orders
    FROM sales_table;    
    """, conn
)

   unique_orders
0           1834